### ISSUE TITLE
Missing source string for translation

### ISSUE THREAD

**Issue by mschnye** [netmex/sqrip-woocommerce#32]
Hi,
I am using Loco Translate to translate text strings to German (Swiss informal).  One source string is missing. 

Use these 6 characters (numbers or letters) as characters 5-10 in CR-references
This is an example of a CR reference with this option enabled, with X-es representing the 6 characters: RF18 XXXX XX12 1231 1231 4703 4

**Comment by netmex** [comment]
Thanks. It's added.

**Comment by mschnye** [comment]
Hi,
found in users some more:

Refunds with sqrip
This iban will be used to generate a sqrip qr code in case of a refund.

**Comment by netmex** [comment]
Thanks. All German text strings should now be fine.

**Comment by mschnye** [comment]
I updated the language file, but still the same.
